root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "build-errors.log"
  delay = 1000

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[screen]
  keep_scroll = true